---
- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Install Java-8
      apt:
        name: openjdk-8-jdk
        update_cache: yes
